// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/ledger-middleware/pkg/db/ent/couponwithdraw"
	"github.com/NpoolPlatform/ledger-middleware/pkg/db/ent/predicate"
)

// CouponWithdrawDelete is the builder for deleting a CouponWithdraw entity.
type CouponWithdrawDelete struct {
	config
	hooks    []Hook
	mutation *CouponWithdrawMutation
}

// Where appends a list predicates to the CouponWithdrawDelete builder.
func (cwd *CouponWithdrawDelete) Where(ps ...predicate.CouponWithdraw) *CouponWithdrawDelete {
	cwd.mutation.Where(ps...)
	return cwd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (cwd *CouponWithdrawDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(cwd.hooks) == 0 {
		affected, err = cwd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*CouponWithdrawMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			cwd.mutation = mutation
			affected, err = cwd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(cwd.hooks) - 1; i >= 0; i-- {
			if cwd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = cwd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, cwd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (cwd *CouponWithdrawDelete) ExecX(ctx context.Context) int {
	n, err := cwd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (cwd *CouponWithdrawDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: couponwithdraw.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint32,
				Column: couponwithdraw.FieldID,
			},
		},
	}
	if ps := cwd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, cwd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	return affected, err
}

// CouponWithdrawDeleteOne is the builder for deleting a single CouponWithdraw entity.
type CouponWithdrawDeleteOne struct {
	cwd *CouponWithdrawDelete
}

// Exec executes the deletion query.
func (cwdo *CouponWithdrawDeleteOne) Exec(ctx context.Context) error {
	n, err := cwdo.cwd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{couponwithdraw.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (cwdo *CouponWithdrawDeleteOne) ExecX(ctx context.Context) {
	cwdo.cwd.ExecX(ctx)
}
