// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/ledger-middleware/pkg/db/ent/ledgerlock"
	"github.com/NpoolPlatform/ledger-middleware/pkg/db/ent/predicate"
)

// LedgerLockQuery is the builder for querying LedgerLock entities.
type LedgerLockQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.LedgerLock
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the LedgerLockQuery builder.
func (llq *LedgerLockQuery) Where(ps ...predicate.LedgerLock) *LedgerLockQuery {
	llq.predicates = append(llq.predicates, ps...)
	return llq
}

// Limit adds a limit step to the query.
func (llq *LedgerLockQuery) Limit(limit int) *LedgerLockQuery {
	llq.limit = &limit
	return llq
}

// Offset adds an offset step to the query.
func (llq *LedgerLockQuery) Offset(offset int) *LedgerLockQuery {
	llq.offset = &offset
	return llq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (llq *LedgerLockQuery) Unique(unique bool) *LedgerLockQuery {
	llq.unique = &unique
	return llq
}

// Order adds an order step to the query.
func (llq *LedgerLockQuery) Order(o ...OrderFunc) *LedgerLockQuery {
	llq.order = append(llq.order, o...)
	return llq
}

// First returns the first LedgerLock entity from the query.
// Returns a *NotFoundError when no LedgerLock was found.
func (llq *LedgerLockQuery) First(ctx context.Context) (*LedgerLock, error) {
	nodes, err := llq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{ledgerlock.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (llq *LedgerLockQuery) FirstX(ctx context.Context) *LedgerLock {
	node, err := llq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first LedgerLock ID from the query.
// Returns a *NotFoundError when no LedgerLock ID was found.
func (llq *LedgerLockQuery) FirstID(ctx context.Context) (id uint32, err error) {
	var ids []uint32
	if ids, err = llq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{ledgerlock.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (llq *LedgerLockQuery) FirstIDX(ctx context.Context) uint32 {
	id, err := llq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single LedgerLock entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one LedgerLock entity is found.
// Returns a *NotFoundError when no LedgerLock entities are found.
func (llq *LedgerLockQuery) Only(ctx context.Context) (*LedgerLock, error) {
	nodes, err := llq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{ledgerlock.Label}
	default:
		return nil, &NotSingularError{ledgerlock.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (llq *LedgerLockQuery) OnlyX(ctx context.Context) *LedgerLock {
	node, err := llq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only LedgerLock ID in the query.
// Returns a *NotSingularError when more than one LedgerLock ID is found.
// Returns a *NotFoundError when no entities are found.
func (llq *LedgerLockQuery) OnlyID(ctx context.Context) (id uint32, err error) {
	var ids []uint32
	if ids, err = llq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{ledgerlock.Label}
	default:
		err = &NotSingularError{ledgerlock.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (llq *LedgerLockQuery) OnlyIDX(ctx context.Context) uint32 {
	id, err := llq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of LedgerLocks.
func (llq *LedgerLockQuery) All(ctx context.Context) ([]*LedgerLock, error) {
	if err := llq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return llq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (llq *LedgerLockQuery) AllX(ctx context.Context) []*LedgerLock {
	nodes, err := llq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of LedgerLock IDs.
func (llq *LedgerLockQuery) IDs(ctx context.Context) ([]uint32, error) {
	var ids []uint32
	if err := llq.Select(ledgerlock.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (llq *LedgerLockQuery) IDsX(ctx context.Context) []uint32 {
	ids, err := llq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (llq *LedgerLockQuery) Count(ctx context.Context) (int, error) {
	if err := llq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return llq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (llq *LedgerLockQuery) CountX(ctx context.Context) int {
	count, err := llq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (llq *LedgerLockQuery) Exist(ctx context.Context) (bool, error) {
	if err := llq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return llq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (llq *LedgerLockQuery) ExistX(ctx context.Context) bool {
	exist, err := llq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the LedgerLockQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (llq *LedgerLockQuery) Clone() *LedgerLockQuery {
	if llq == nil {
		return nil
	}
	return &LedgerLockQuery{
		config:     llq.config,
		limit:      llq.limit,
		offset:     llq.offset,
		order:      append([]OrderFunc{}, llq.order...),
		predicates: append([]predicate.LedgerLock{}, llq.predicates...),
		// clone intermediate query.
		sql:    llq.sql.Clone(),
		path:   llq.path,
		unique: llq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt uint32 `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.LedgerLock.Query().
//		GroupBy(ledgerlock.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (llq *LedgerLockQuery) GroupBy(field string, fields ...string) *LedgerLockGroupBy {
	grbuild := &LedgerLockGroupBy{config: llq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := llq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return llq.sqlQuery(ctx), nil
	}
	grbuild.label = ledgerlock.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt uint32 `json:"created_at,omitempty"`
//	}
//
//	client.LedgerLock.Query().
//		Select(ledgerlock.FieldCreatedAt).
//		Scan(ctx, &v)
//
func (llq *LedgerLockQuery) Select(fields ...string) *LedgerLockSelect {
	llq.fields = append(llq.fields, fields...)
	selbuild := &LedgerLockSelect{LedgerLockQuery: llq}
	selbuild.label = ledgerlock.Label
	selbuild.flds, selbuild.scan = &llq.fields, selbuild.Scan
	return selbuild
}

func (llq *LedgerLockQuery) prepareQuery(ctx context.Context) error {
	for _, f := range llq.fields {
		if !ledgerlock.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if llq.path != nil {
		prev, err := llq.path(ctx)
		if err != nil {
			return err
		}
		llq.sql = prev
	}
	if ledgerlock.Policy == nil {
		return errors.New("ent: uninitialized ledgerlock.Policy (forgotten import ent/runtime?)")
	}
	if err := ledgerlock.Policy.EvalQuery(ctx, llq); err != nil {
		return err
	}
	return nil
}

func (llq *LedgerLockQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*LedgerLock, error) {
	var (
		nodes = []*LedgerLock{}
		_spec = llq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		return (*LedgerLock).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		node := &LedgerLock{config: llq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	if len(llq.modifiers) > 0 {
		_spec.Modifiers = llq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, llq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (llq *LedgerLockQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := llq.querySpec()
	if len(llq.modifiers) > 0 {
		_spec.Modifiers = llq.modifiers
	}
	_spec.Node.Columns = llq.fields
	if len(llq.fields) > 0 {
		_spec.Unique = llq.unique != nil && *llq.unique
	}
	return sqlgraph.CountNodes(ctx, llq.driver, _spec)
}

func (llq *LedgerLockQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := llq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (llq *LedgerLockQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   ledgerlock.Table,
			Columns: ledgerlock.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint32,
				Column: ledgerlock.FieldID,
			},
		},
		From:   llq.sql,
		Unique: true,
	}
	if unique := llq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := llq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, ledgerlock.FieldID)
		for i := range fields {
			if fields[i] != ledgerlock.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := llq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := llq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := llq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := llq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (llq *LedgerLockQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(llq.driver.Dialect())
	t1 := builder.Table(ledgerlock.Table)
	columns := llq.fields
	if len(columns) == 0 {
		columns = ledgerlock.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if llq.sql != nil {
		selector = llq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if llq.unique != nil && *llq.unique {
		selector.Distinct()
	}
	for _, m := range llq.modifiers {
		m(selector)
	}
	for _, p := range llq.predicates {
		p(selector)
	}
	for _, p := range llq.order {
		p(selector)
	}
	if offset := llq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := llq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (llq *LedgerLockQuery) ForUpdate(opts ...sql.LockOption) *LedgerLockQuery {
	if llq.driver.Dialect() == dialect.Postgres {
		llq.Unique(false)
	}
	llq.modifiers = append(llq.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return llq
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (llq *LedgerLockQuery) ForShare(opts ...sql.LockOption) *LedgerLockQuery {
	if llq.driver.Dialect() == dialect.Postgres {
		llq.Unique(false)
	}
	llq.modifiers = append(llq.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return llq
}

// LedgerLockGroupBy is the group-by builder for LedgerLock entities.
type LedgerLockGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (llgb *LedgerLockGroupBy) Aggregate(fns ...AggregateFunc) *LedgerLockGroupBy {
	llgb.fns = append(llgb.fns, fns...)
	return llgb
}

// Scan applies the group-by query and scans the result into the given value.
func (llgb *LedgerLockGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := llgb.path(ctx)
	if err != nil {
		return err
	}
	llgb.sql = query
	return llgb.sqlScan(ctx, v)
}

func (llgb *LedgerLockGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range llgb.fields {
		if !ledgerlock.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := llgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := llgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (llgb *LedgerLockGroupBy) sqlQuery() *sql.Selector {
	selector := llgb.sql.Select()
	aggregation := make([]string, 0, len(llgb.fns))
	for _, fn := range llgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(llgb.fields)+len(llgb.fns))
		for _, f := range llgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(llgb.fields...)...)
}

// LedgerLockSelect is the builder for selecting fields of LedgerLock entities.
type LedgerLockSelect struct {
	*LedgerLockQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (lls *LedgerLockSelect) Scan(ctx context.Context, v interface{}) error {
	if err := lls.prepareQuery(ctx); err != nil {
		return err
	}
	lls.sql = lls.LedgerLockQuery.sqlQuery(ctx)
	return lls.sqlScan(ctx, v)
}

func (lls *LedgerLockSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := lls.sql.Query()
	if err := lls.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
