// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/ledger-middleware/pkg/db/ent/miningdetail"
	"github.com/NpoolPlatform/ledger-middleware/pkg/db/ent/predicate"
	"github.com/google/uuid"
)

// MiningDetailQuery is the builder for querying MiningDetail entities.
type MiningDetailQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.MiningDetail
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the MiningDetailQuery builder.
func (mdq *MiningDetailQuery) Where(ps ...predicate.MiningDetail) *MiningDetailQuery {
	mdq.predicates = append(mdq.predicates, ps...)
	return mdq
}

// Limit adds a limit step to the query.
func (mdq *MiningDetailQuery) Limit(limit int) *MiningDetailQuery {
	mdq.limit = &limit
	return mdq
}

// Offset adds an offset step to the query.
func (mdq *MiningDetailQuery) Offset(offset int) *MiningDetailQuery {
	mdq.offset = &offset
	return mdq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (mdq *MiningDetailQuery) Unique(unique bool) *MiningDetailQuery {
	mdq.unique = &unique
	return mdq
}

// Order adds an order step to the query.
func (mdq *MiningDetailQuery) Order(o ...OrderFunc) *MiningDetailQuery {
	mdq.order = append(mdq.order, o...)
	return mdq
}

// First returns the first MiningDetail entity from the query.
// Returns a *NotFoundError when no MiningDetail was found.
func (mdq *MiningDetailQuery) First(ctx context.Context) (*MiningDetail, error) {
	nodes, err := mdq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{miningdetail.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (mdq *MiningDetailQuery) FirstX(ctx context.Context) *MiningDetail {
	node, err := mdq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first MiningDetail ID from the query.
// Returns a *NotFoundError when no MiningDetail ID was found.
func (mdq *MiningDetailQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = mdq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{miningdetail.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (mdq *MiningDetailQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := mdq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single MiningDetail entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one MiningDetail entity is found.
// Returns a *NotFoundError when no MiningDetail entities are found.
func (mdq *MiningDetailQuery) Only(ctx context.Context) (*MiningDetail, error) {
	nodes, err := mdq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{miningdetail.Label}
	default:
		return nil, &NotSingularError{miningdetail.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (mdq *MiningDetailQuery) OnlyX(ctx context.Context) *MiningDetail {
	node, err := mdq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only MiningDetail ID in the query.
// Returns a *NotSingularError when more than one MiningDetail ID is found.
// Returns a *NotFoundError when no entities are found.
func (mdq *MiningDetailQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = mdq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{miningdetail.Label}
	default:
		err = &NotSingularError{miningdetail.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (mdq *MiningDetailQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := mdq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of MiningDetails.
func (mdq *MiningDetailQuery) All(ctx context.Context) ([]*MiningDetail, error) {
	if err := mdq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return mdq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (mdq *MiningDetailQuery) AllX(ctx context.Context) []*MiningDetail {
	nodes, err := mdq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of MiningDetail IDs.
func (mdq *MiningDetailQuery) IDs(ctx context.Context) ([]uuid.UUID, error) {
	var ids []uuid.UUID
	if err := mdq.Select(miningdetail.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (mdq *MiningDetailQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := mdq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (mdq *MiningDetailQuery) Count(ctx context.Context) (int, error) {
	if err := mdq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return mdq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (mdq *MiningDetailQuery) CountX(ctx context.Context) int {
	count, err := mdq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (mdq *MiningDetailQuery) Exist(ctx context.Context) (bool, error) {
	if err := mdq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return mdq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (mdq *MiningDetailQuery) ExistX(ctx context.Context) bool {
	exist, err := mdq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the MiningDetailQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (mdq *MiningDetailQuery) Clone() *MiningDetailQuery {
	if mdq == nil {
		return nil
	}
	return &MiningDetailQuery{
		config:     mdq.config,
		limit:      mdq.limit,
		offset:     mdq.offset,
		order:      append([]OrderFunc{}, mdq.order...),
		predicates: append([]predicate.MiningDetail{}, mdq.predicates...),
		// clone intermediate query.
		sql:    mdq.sql.Clone(),
		path:   mdq.path,
		unique: mdq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt uint32 `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.MiningDetail.Query().
//		GroupBy(miningdetail.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (mdq *MiningDetailQuery) GroupBy(field string, fields ...string) *MiningDetailGroupBy {
	grbuild := &MiningDetailGroupBy{config: mdq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := mdq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return mdq.sqlQuery(ctx), nil
	}
	grbuild.label = miningdetail.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt uint32 `json:"created_at,omitempty"`
//	}
//
//	client.MiningDetail.Query().
//		Select(miningdetail.FieldCreatedAt).
//		Scan(ctx, &v)
//
func (mdq *MiningDetailQuery) Select(fields ...string) *MiningDetailSelect {
	mdq.fields = append(mdq.fields, fields...)
	selbuild := &MiningDetailSelect{MiningDetailQuery: mdq}
	selbuild.label = miningdetail.Label
	selbuild.flds, selbuild.scan = &mdq.fields, selbuild.Scan
	return selbuild
}

func (mdq *MiningDetailQuery) prepareQuery(ctx context.Context) error {
	for _, f := range mdq.fields {
		if !miningdetail.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if mdq.path != nil {
		prev, err := mdq.path(ctx)
		if err != nil {
			return err
		}
		mdq.sql = prev
	}
	if miningdetail.Policy == nil {
		return errors.New("ent: uninitialized miningdetail.Policy (forgotten import ent/runtime?)")
	}
	if err := miningdetail.Policy.EvalQuery(ctx, mdq); err != nil {
		return err
	}
	return nil
}

func (mdq *MiningDetailQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*MiningDetail, error) {
	var (
		nodes = []*MiningDetail{}
		_spec = mdq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		return (*MiningDetail).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		node := &MiningDetail{config: mdq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	if len(mdq.modifiers) > 0 {
		_spec.Modifiers = mdq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, mdq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (mdq *MiningDetailQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := mdq.querySpec()
	if len(mdq.modifiers) > 0 {
		_spec.Modifiers = mdq.modifiers
	}
	_spec.Node.Columns = mdq.fields
	if len(mdq.fields) > 0 {
		_spec.Unique = mdq.unique != nil && *mdq.unique
	}
	return sqlgraph.CountNodes(ctx, mdq.driver, _spec)
}

func (mdq *MiningDetailQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := mdq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (mdq *MiningDetailQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   miningdetail.Table,
			Columns: miningdetail.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: miningdetail.FieldID,
			},
		},
		From:   mdq.sql,
		Unique: true,
	}
	if unique := mdq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := mdq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, miningdetail.FieldID)
		for i := range fields {
			if fields[i] != miningdetail.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := mdq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := mdq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := mdq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := mdq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (mdq *MiningDetailQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(mdq.driver.Dialect())
	t1 := builder.Table(miningdetail.Table)
	columns := mdq.fields
	if len(columns) == 0 {
		columns = miningdetail.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if mdq.sql != nil {
		selector = mdq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if mdq.unique != nil && *mdq.unique {
		selector.Distinct()
	}
	for _, m := range mdq.modifiers {
		m(selector)
	}
	for _, p := range mdq.predicates {
		p(selector)
	}
	for _, p := range mdq.order {
		p(selector)
	}
	if offset := mdq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := mdq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (mdq *MiningDetailQuery) ForUpdate(opts ...sql.LockOption) *MiningDetailQuery {
	if mdq.driver.Dialect() == dialect.Postgres {
		mdq.Unique(false)
	}
	mdq.modifiers = append(mdq.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return mdq
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (mdq *MiningDetailQuery) ForShare(opts ...sql.LockOption) *MiningDetailQuery {
	if mdq.driver.Dialect() == dialect.Postgres {
		mdq.Unique(false)
	}
	mdq.modifiers = append(mdq.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return mdq
}

// MiningDetailGroupBy is the group-by builder for MiningDetail entities.
type MiningDetailGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (mdgb *MiningDetailGroupBy) Aggregate(fns ...AggregateFunc) *MiningDetailGroupBy {
	mdgb.fns = append(mdgb.fns, fns...)
	return mdgb
}

// Scan applies the group-by query and scans the result into the given value.
func (mdgb *MiningDetailGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := mdgb.path(ctx)
	if err != nil {
		return err
	}
	mdgb.sql = query
	return mdgb.sqlScan(ctx, v)
}

func (mdgb *MiningDetailGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range mdgb.fields {
		if !miningdetail.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := mdgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := mdgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (mdgb *MiningDetailGroupBy) sqlQuery() *sql.Selector {
	selector := mdgb.sql.Select()
	aggregation := make([]string, 0, len(mdgb.fns))
	for _, fn := range mdgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(mdgb.fields)+len(mdgb.fns))
		for _, f := range mdgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(mdgb.fields...)...)
}

// MiningDetailSelect is the builder for selecting fields of MiningDetail entities.
type MiningDetailSelect struct {
	*MiningDetailQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (mds *MiningDetailSelect) Scan(ctx context.Context, v interface{}) error {
	if err := mds.prepareQuery(ctx); err != nil {
		return err
	}
	mds.sql = mds.MiningDetailQuery.sqlQuery(ctx)
	return mds.sqlScan(ctx, v)
}

func (mds *MiningDetailSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := mds.sql.Query()
	if err := mds.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
