// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/ledger-middleware/pkg/db/ent/miningunsold"
	"github.com/NpoolPlatform/ledger-middleware/pkg/db/ent/predicate"
	"github.com/google/uuid"
)

// MiningUnsoldQuery is the builder for querying MiningUnsold entities.
type MiningUnsoldQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.MiningUnsold
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the MiningUnsoldQuery builder.
func (muq *MiningUnsoldQuery) Where(ps ...predicate.MiningUnsold) *MiningUnsoldQuery {
	muq.predicates = append(muq.predicates, ps...)
	return muq
}

// Limit adds a limit step to the query.
func (muq *MiningUnsoldQuery) Limit(limit int) *MiningUnsoldQuery {
	muq.limit = &limit
	return muq
}

// Offset adds an offset step to the query.
func (muq *MiningUnsoldQuery) Offset(offset int) *MiningUnsoldQuery {
	muq.offset = &offset
	return muq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (muq *MiningUnsoldQuery) Unique(unique bool) *MiningUnsoldQuery {
	muq.unique = &unique
	return muq
}

// Order adds an order step to the query.
func (muq *MiningUnsoldQuery) Order(o ...OrderFunc) *MiningUnsoldQuery {
	muq.order = append(muq.order, o...)
	return muq
}

// First returns the first MiningUnsold entity from the query.
// Returns a *NotFoundError when no MiningUnsold was found.
func (muq *MiningUnsoldQuery) First(ctx context.Context) (*MiningUnsold, error) {
	nodes, err := muq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{miningunsold.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (muq *MiningUnsoldQuery) FirstX(ctx context.Context) *MiningUnsold {
	node, err := muq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first MiningUnsold ID from the query.
// Returns a *NotFoundError when no MiningUnsold ID was found.
func (muq *MiningUnsoldQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = muq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{miningunsold.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (muq *MiningUnsoldQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := muq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single MiningUnsold entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one MiningUnsold entity is found.
// Returns a *NotFoundError when no MiningUnsold entities are found.
func (muq *MiningUnsoldQuery) Only(ctx context.Context) (*MiningUnsold, error) {
	nodes, err := muq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{miningunsold.Label}
	default:
		return nil, &NotSingularError{miningunsold.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (muq *MiningUnsoldQuery) OnlyX(ctx context.Context) *MiningUnsold {
	node, err := muq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only MiningUnsold ID in the query.
// Returns a *NotSingularError when more than one MiningUnsold ID is found.
// Returns a *NotFoundError when no entities are found.
func (muq *MiningUnsoldQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = muq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{miningunsold.Label}
	default:
		err = &NotSingularError{miningunsold.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (muq *MiningUnsoldQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := muq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of MiningUnsolds.
func (muq *MiningUnsoldQuery) All(ctx context.Context) ([]*MiningUnsold, error) {
	if err := muq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return muq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (muq *MiningUnsoldQuery) AllX(ctx context.Context) []*MiningUnsold {
	nodes, err := muq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of MiningUnsold IDs.
func (muq *MiningUnsoldQuery) IDs(ctx context.Context) ([]uuid.UUID, error) {
	var ids []uuid.UUID
	if err := muq.Select(miningunsold.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (muq *MiningUnsoldQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := muq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (muq *MiningUnsoldQuery) Count(ctx context.Context) (int, error) {
	if err := muq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return muq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (muq *MiningUnsoldQuery) CountX(ctx context.Context) int {
	count, err := muq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (muq *MiningUnsoldQuery) Exist(ctx context.Context) (bool, error) {
	if err := muq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return muq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (muq *MiningUnsoldQuery) ExistX(ctx context.Context) bool {
	exist, err := muq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the MiningUnsoldQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (muq *MiningUnsoldQuery) Clone() *MiningUnsoldQuery {
	if muq == nil {
		return nil
	}
	return &MiningUnsoldQuery{
		config:     muq.config,
		limit:      muq.limit,
		offset:     muq.offset,
		order:      append([]OrderFunc{}, muq.order...),
		predicates: append([]predicate.MiningUnsold{}, muq.predicates...),
		// clone intermediate query.
		sql:    muq.sql.Clone(),
		path:   muq.path,
		unique: muq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt uint32 `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.MiningUnsold.Query().
//		GroupBy(miningunsold.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (muq *MiningUnsoldQuery) GroupBy(field string, fields ...string) *MiningUnsoldGroupBy {
	grbuild := &MiningUnsoldGroupBy{config: muq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := muq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return muq.sqlQuery(ctx), nil
	}
	grbuild.label = miningunsold.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt uint32 `json:"created_at,omitempty"`
//	}
//
//	client.MiningUnsold.Query().
//		Select(miningunsold.FieldCreatedAt).
//		Scan(ctx, &v)
//
func (muq *MiningUnsoldQuery) Select(fields ...string) *MiningUnsoldSelect {
	muq.fields = append(muq.fields, fields...)
	selbuild := &MiningUnsoldSelect{MiningUnsoldQuery: muq}
	selbuild.label = miningunsold.Label
	selbuild.flds, selbuild.scan = &muq.fields, selbuild.Scan
	return selbuild
}

func (muq *MiningUnsoldQuery) prepareQuery(ctx context.Context) error {
	for _, f := range muq.fields {
		if !miningunsold.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if muq.path != nil {
		prev, err := muq.path(ctx)
		if err != nil {
			return err
		}
		muq.sql = prev
	}
	if miningunsold.Policy == nil {
		return errors.New("ent: uninitialized miningunsold.Policy (forgotten import ent/runtime?)")
	}
	if err := miningunsold.Policy.EvalQuery(ctx, muq); err != nil {
		return err
	}
	return nil
}

func (muq *MiningUnsoldQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*MiningUnsold, error) {
	var (
		nodes = []*MiningUnsold{}
		_spec = muq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		return (*MiningUnsold).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		node := &MiningUnsold{config: muq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	if len(muq.modifiers) > 0 {
		_spec.Modifiers = muq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, muq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (muq *MiningUnsoldQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := muq.querySpec()
	if len(muq.modifiers) > 0 {
		_spec.Modifiers = muq.modifiers
	}
	_spec.Node.Columns = muq.fields
	if len(muq.fields) > 0 {
		_spec.Unique = muq.unique != nil && *muq.unique
	}
	return sqlgraph.CountNodes(ctx, muq.driver, _spec)
}

func (muq *MiningUnsoldQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := muq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (muq *MiningUnsoldQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   miningunsold.Table,
			Columns: miningunsold.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: miningunsold.FieldID,
			},
		},
		From:   muq.sql,
		Unique: true,
	}
	if unique := muq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := muq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, miningunsold.FieldID)
		for i := range fields {
			if fields[i] != miningunsold.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := muq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := muq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := muq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := muq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (muq *MiningUnsoldQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(muq.driver.Dialect())
	t1 := builder.Table(miningunsold.Table)
	columns := muq.fields
	if len(columns) == 0 {
		columns = miningunsold.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if muq.sql != nil {
		selector = muq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if muq.unique != nil && *muq.unique {
		selector.Distinct()
	}
	for _, m := range muq.modifiers {
		m(selector)
	}
	for _, p := range muq.predicates {
		p(selector)
	}
	for _, p := range muq.order {
		p(selector)
	}
	if offset := muq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := muq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (muq *MiningUnsoldQuery) ForUpdate(opts ...sql.LockOption) *MiningUnsoldQuery {
	if muq.driver.Dialect() == dialect.Postgres {
		muq.Unique(false)
	}
	muq.modifiers = append(muq.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return muq
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (muq *MiningUnsoldQuery) ForShare(opts ...sql.LockOption) *MiningUnsoldQuery {
	if muq.driver.Dialect() == dialect.Postgres {
		muq.Unique(false)
	}
	muq.modifiers = append(muq.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return muq
}

// MiningUnsoldGroupBy is the group-by builder for MiningUnsold entities.
type MiningUnsoldGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (mugb *MiningUnsoldGroupBy) Aggregate(fns ...AggregateFunc) *MiningUnsoldGroupBy {
	mugb.fns = append(mugb.fns, fns...)
	return mugb
}

// Scan applies the group-by query and scans the result into the given value.
func (mugb *MiningUnsoldGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := mugb.path(ctx)
	if err != nil {
		return err
	}
	mugb.sql = query
	return mugb.sqlScan(ctx, v)
}

func (mugb *MiningUnsoldGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range mugb.fields {
		if !miningunsold.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := mugb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := mugb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (mugb *MiningUnsoldGroupBy) sqlQuery() *sql.Selector {
	selector := mugb.sql.Select()
	aggregation := make([]string, 0, len(mugb.fns))
	for _, fn := range mugb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(mugb.fields)+len(mugb.fns))
		for _, f := range mugb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(mugb.fields...)...)
}

// MiningUnsoldSelect is the builder for selecting fields of MiningUnsold entities.
type MiningUnsoldSelect struct {
	*MiningUnsoldQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (mus *MiningUnsoldSelect) Scan(ctx context.Context, v interface{}) error {
	if err := mus.prepareQuery(ctx); err != nil {
		return err
	}
	mus.sql = mus.MiningUnsoldQuery.sqlQuery(ctx)
	return mus.sqlScan(ctx, v)
}

func (mus *MiningUnsoldSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := mus.sql.Query()
	if err := mus.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
