// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/ledger-middleware/pkg/db/ent/predicate"
	"github.com/NpoolPlatform/ledger-middleware/pkg/db/ent/unsoldstatement"
	"github.com/google/uuid"
)

// UnsoldStatementQuery is the builder for querying UnsoldStatement entities.
type UnsoldStatementQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.UnsoldStatement
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the UnsoldStatementQuery builder.
func (usq *UnsoldStatementQuery) Where(ps ...predicate.UnsoldStatement) *UnsoldStatementQuery {
	usq.predicates = append(usq.predicates, ps...)
	return usq
}

// Limit adds a limit step to the query.
func (usq *UnsoldStatementQuery) Limit(limit int) *UnsoldStatementQuery {
	usq.limit = &limit
	return usq
}

// Offset adds an offset step to the query.
func (usq *UnsoldStatementQuery) Offset(offset int) *UnsoldStatementQuery {
	usq.offset = &offset
	return usq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (usq *UnsoldStatementQuery) Unique(unique bool) *UnsoldStatementQuery {
	usq.unique = &unique
	return usq
}

// Order adds an order step to the query.
func (usq *UnsoldStatementQuery) Order(o ...OrderFunc) *UnsoldStatementQuery {
	usq.order = append(usq.order, o...)
	return usq
}

// First returns the first UnsoldStatement entity from the query.
// Returns a *NotFoundError when no UnsoldStatement was found.
func (usq *UnsoldStatementQuery) First(ctx context.Context) (*UnsoldStatement, error) {
	nodes, err := usq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{unsoldstatement.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (usq *UnsoldStatementQuery) FirstX(ctx context.Context) *UnsoldStatement {
	node, err := usq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first UnsoldStatement ID from the query.
// Returns a *NotFoundError when no UnsoldStatement ID was found.
func (usq *UnsoldStatementQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = usq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{unsoldstatement.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (usq *UnsoldStatementQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := usq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single UnsoldStatement entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one UnsoldStatement entity is found.
// Returns a *NotFoundError when no UnsoldStatement entities are found.
func (usq *UnsoldStatementQuery) Only(ctx context.Context) (*UnsoldStatement, error) {
	nodes, err := usq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{unsoldstatement.Label}
	default:
		return nil, &NotSingularError{unsoldstatement.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (usq *UnsoldStatementQuery) OnlyX(ctx context.Context) *UnsoldStatement {
	node, err := usq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only UnsoldStatement ID in the query.
// Returns a *NotSingularError when more than one UnsoldStatement ID is found.
// Returns a *NotFoundError when no entities are found.
func (usq *UnsoldStatementQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = usq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{unsoldstatement.Label}
	default:
		err = &NotSingularError{unsoldstatement.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (usq *UnsoldStatementQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := usq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of UnsoldStatements.
func (usq *UnsoldStatementQuery) All(ctx context.Context) ([]*UnsoldStatement, error) {
	if err := usq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return usq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (usq *UnsoldStatementQuery) AllX(ctx context.Context) []*UnsoldStatement {
	nodes, err := usq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of UnsoldStatement IDs.
func (usq *UnsoldStatementQuery) IDs(ctx context.Context) ([]uuid.UUID, error) {
	var ids []uuid.UUID
	if err := usq.Select(unsoldstatement.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (usq *UnsoldStatementQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := usq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (usq *UnsoldStatementQuery) Count(ctx context.Context) (int, error) {
	if err := usq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return usq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (usq *UnsoldStatementQuery) CountX(ctx context.Context) int {
	count, err := usq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (usq *UnsoldStatementQuery) Exist(ctx context.Context) (bool, error) {
	if err := usq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return usq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (usq *UnsoldStatementQuery) ExistX(ctx context.Context) bool {
	exist, err := usq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the UnsoldStatementQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (usq *UnsoldStatementQuery) Clone() *UnsoldStatementQuery {
	if usq == nil {
		return nil
	}
	return &UnsoldStatementQuery{
		config:     usq.config,
		limit:      usq.limit,
		offset:     usq.offset,
		order:      append([]OrderFunc{}, usq.order...),
		predicates: append([]predicate.UnsoldStatement{}, usq.predicates...),
		// clone intermediate query.
		sql:    usq.sql.Clone(),
		path:   usq.path,
		unique: usq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt uint32 `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.UnsoldStatement.Query().
//		GroupBy(unsoldstatement.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (usq *UnsoldStatementQuery) GroupBy(field string, fields ...string) *UnsoldStatementGroupBy {
	grbuild := &UnsoldStatementGroupBy{config: usq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := usq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return usq.sqlQuery(ctx), nil
	}
	grbuild.label = unsoldstatement.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt uint32 `json:"created_at,omitempty"`
//	}
//
//	client.UnsoldStatement.Query().
//		Select(unsoldstatement.FieldCreatedAt).
//		Scan(ctx, &v)
//
func (usq *UnsoldStatementQuery) Select(fields ...string) *UnsoldStatementSelect {
	usq.fields = append(usq.fields, fields...)
	selbuild := &UnsoldStatementSelect{UnsoldStatementQuery: usq}
	selbuild.label = unsoldstatement.Label
	selbuild.flds, selbuild.scan = &usq.fields, selbuild.Scan
	return selbuild
}

func (usq *UnsoldStatementQuery) prepareQuery(ctx context.Context) error {
	for _, f := range usq.fields {
		if !unsoldstatement.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if usq.path != nil {
		prev, err := usq.path(ctx)
		if err != nil {
			return err
		}
		usq.sql = prev
	}
	if unsoldstatement.Policy == nil {
		return errors.New("ent: uninitialized unsoldstatement.Policy (forgotten import ent/runtime?)")
	}
	if err := unsoldstatement.Policy.EvalQuery(ctx, usq); err != nil {
		return err
	}
	return nil
}

func (usq *UnsoldStatementQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*UnsoldStatement, error) {
	var (
		nodes = []*UnsoldStatement{}
		_spec = usq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		return (*UnsoldStatement).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		node := &UnsoldStatement{config: usq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	if len(usq.modifiers) > 0 {
		_spec.Modifiers = usq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, usq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (usq *UnsoldStatementQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := usq.querySpec()
	if len(usq.modifiers) > 0 {
		_spec.Modifiers = usq.modifiers
	}
	_spec.Node.Columns = usq.fields
	if len(usq.fields) > 0 {
		_spec.Unique = usq.unique != nil && *usq.unique
	}
	return sqlgraph.CountNodes(ctx, usq.driver, _spec)
}

func (usq *UnsoldStatementQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := usq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (usq *UnsoldStatementQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   unsoldstatement.Table,
			Columns: unsoldstatement.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: unsoldstatement.FieldID,
			},
		},
		From:   usq.sql,
		Unique: true,
	}
	if unique := usq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := usq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, unsoldstatement.FieldID)
		for i := range fields {
			if fields[i] != unsoldstatement.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := usq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := usq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := usq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := usq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (usq *UnsoldStatementQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(usq.driver.Dialect())
	t1 := builder.Table(unsoldstatement.Table)
	columns := usq.fields
	if len(columns) == 0 {
		columns = unsoldstatement.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if usq.sql != nil {
		selector = usq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if usq.unique != nil && *usq.unique {
		selector.Distinct()
	}
	for _, m := range usq.modifiers {
		m(selector)
	}
	for _, p := range usq.predicates {
		p(selector)
	}
	for _, p := range usq.order {
		p(selector)
	}
	if offset := usq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := usq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (usq *UnsoldStatementQuery) ForUpdate(opts ...sql.LockOption) *UnsoldStatementQuery {
	if usq.driver.Dialect() == dialect.Postgres {
		usq.Unique(false)
	}
	usq.modifiers = append(usq.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return usq
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (usq *UnsoldStatementQuery) ForShare(opts ...sql.LockOption) *UnsoldStatementQuery {
	if usq.driver.Dialect() == dialect.Postgres {
		usq.Unique(false)
	}
	usq.modifiers = append(usq.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return usq
}

// UnsoldStatementGroupBy is the group-by builder for UnsoldStatement entities.
type UnsoldStatementGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (usgb *UnsoldStatementGroupBy) Aggregate(fns ...AggregateFunc) *UnsoldStatementGroupBy {
	usgb.fns = append(usgb.fns, fns...)
	return usgb
}

// Scan applies the group-by query and scans the result into the given value.
func (usgb *UnsoldStatementGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := usgb.path(ctx)
	if err != nil {
		return err
	}
	usgb.sql = query
	return usgb.sqlScan(ctx, v)
}

func (usgb *UnsoldStatementGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range usgb.fields {
		if !unsoldstatement.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := usgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := usgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (usgb *UnsoldStatementGroupBy) sqlQuery() *sql.Selector {
	selector := usgb.sql.Select()
	aggregation := make([]string, 0, len(usgb.fns))
	for _, fn := range usgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(usgb.fields)+len(usgb.fns))
		for _, f := range usgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(usgb.fields...)...)
}

// UnsoldStatementSelect is the builder for selecting fields of UnsoldStatement entities.
type UnsoldStatementSelect struct {
	*UnsoldStatementQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (uss *UnsoldStatementSelect) Scan(ctx context.Context, v interface{}) error {
	if err := uss.prepareQuery(ctx); err != nil {
		return err
	}
	uss.sql = uss.UnsoldStatementQuery.sqlQuery(ctx)
	return uss.sqlScan(ctx, v)
}

func (uss *UnsoldStatementSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := uss.sql.Query()
	if err := uss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
