// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// GoodLedger is the predicate function for goodledger builders.
type GoodLedger func(*sql.Selector)

// GoodStatement is the predicate function for goodstatement builders.
type GoodStatement func(*sql.Selector)

// Ledger is the predicate function for ledger builders.
type Ledger func(*sql.Selector)

// Profit is the predicate function for profit builders.
type Profit func(*sql.Selector)

// Statement is the predicate function for statement builders.
type Statement func(*sql.Selector)

// UnsoldStatement is the predicate function for unsoldstatement builders.
type UnsoldStatement func(*sql.Selector)

// Withdraw is the predicate function for withdraw builders.
type Withdraw func(*sql.Selector)
